sudo: required
services:
  - docker


before_install:
  - docker build -t nayaunglin/react-test -f ./client/Dockerfile.dev ./client
  

script:
  - docker run nayaunglin/react-test npm test -- --coverage


after-success:
  - docker build -t nayaunglin/multi-client ./client
  - docker build -t nayaunglin/multi-nginx ./nginx
  - docker build -t nayaunglin/multi-server ./server
  - docker build -t nayaunglin/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nayaunglin/multi-client
  - docker push nayaunglin/multi-nginx
  - docker push nayaunglin/multi-server
  - docker push nayaunglin/multi-worker




